version: "3.9"

services:
  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: "php"
    ports:
      - "9000:9000"
    volumes:
      - ./src/:/app
    depends_on:
      - db
  db:
    build:
      context: ./docker/db
      dockerfile: Dockerfile
    container_name: "db"
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      MYSQL_DATABASE: database
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      TZ: "Asia/Tokyo"
    volumes:
      - mysql-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    container_name: "phpmyadmin"
    ports:
      - ${PHPMYADMIN_PORT}:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS="db"
      - PMA_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - ./docker/phpmyadmin/sessions:/sessions
  web:
    build:
      context: ./docker/web
      dockerfile: Dockerfile
    container_name: "web-server"
    ports:
      - ${NGINX_PORT}:80
    depends_on:
      - php
      - mailhog
    volumes:
      - ./src/:/app

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - ${MAILHOG_PORT}:8025
    environment:
      MH_STORAGE: maildir
      MH_MAILDIR_PATH: /tmp
    volumes:
      - maildir:/tmp



volumes:
  mysql-data:
  maildir: {}